# Change these first
owner: a4649 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main NAS
    url: $SECRET_SITE
  - name: Seconds NAS
    url: $SECRET_SITE2

status-website:
  theme: ocean
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Systems status"
  introMessage: This page is using the open-source code from [Upptime GitHub repository](https://github.com/upptime/upptime).
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
